### ISSUE TITLE
fanatical.com - ##.slick-track filter

### ISSUE THREAD

**Issue by AmperAndSand** [endolith/clickbait#2]
An issue occurs with the `##.slick-track` filter on `https://www.fanatical.com/`.

In the attached screenshot, the space occupied by the encircled part should be showing an image. It doesn't appear due to the `##.slick-track` filter. This can be remedied by adding the `fanatical.com#@#.slick-track` filter to whitelist the filter on fanatical.com.

![screenshot](https://user-images.githubusercontent.com/1404745/48662139-9638ff80-eab8-11e8-9f23-3e020925c408.png)

**Comment by endolith** [comment]
Oh, I didn't know anyone actually used this.  :D  Ok I'll add it.
