### ISSUE TITLE
nederob.nl - ##.featured-content filter

### ISSUE THREAD

**Issue by AmperAndSand** [endolith/clickbait#4]
Sample URL: https://www.nederob.nl/2019/09/09/brave-browser-most-popular-in-japan/ 

The article at the above webpage won't appear due to the `##.featured-content` filter. This can be remedied by adding the `nederob.nl#@#.featured-content` filter. This will whitelist the filter on nederob.nl.

**Comment by endolith** [comment]
Fixed in 3259b149962d778e04251cc84ed9c40e8bcc00c3
